# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f4777073c6c594e2730cd24998a1845c86d74fef2b03bf6f75c82468b6f368d3e90cd5b6a8ff159a8fdd89ccdc50d71658181659efded47c3e4bcefd50788c

test:
  secret_key_base: ee0131708b02707a1088f75b6280b1e405c5bab2aa3f410bf8d13072e0df5dcbf3aa72c1b514a3c62c026e62da69618c5aabfc9ed32e821ac4149c28ab7b99bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
